app = 'bankend-tlgm-2p'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  idle_timeout = '300s'

  # CONFIGURACIÓN PARA EVITAR EL ERROR PM05
  [[http_service.checks]]
    grace_period = "50s"  # Aumentado a 50s para dar tiempo de carga total
    interval = "20s"      # Revisar cada 20s después del arranque
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
