app = 'bankend-tlgm-2p'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # Tiempo que espera antes de apagar la app por inactividad (5 min)
  idle_timeout = '300s'

  [[http_service.checks]]
    grace_period = "30s" # Tiempo de espera inicial para que Gunicorn levante
    interval = "15s"     # Frecuencia de revisión
    method = "GET"
    timeout = "5s"
    path = "/health"    # ESTA RUTA DEBE EXISTIR EN TU main.py

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
